#!/bin/bash
root_dir=$(cd `dirname $0`/.. && pwd -P)
echo $root_dir
nw_dir="/media/dataj/jianjia_nwjs55/src/out/nw"

cp "$nw_dir/nw" "$root_dir/nwjs/nw"
cp  -r "$nw_dir/lib" "$root_dir/nwjs/"
cp "$nw_dir/v8_context_snapshot.bin" "$root_dir/nwjs/v8_context_snapshot.bin"
